### ISSUE TITLE
How to move windows in the overview to another workspace?

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Desktop-Cube#11]
_The original issue moved to #18_

**Comment by uudruid74** [comment]
Normally on Gnome, you can drag windows between workspaces.  It is unclear how to go about doing this with this plugin active.  Either this feature needs to be implemented or some other intuitive way to move windows between workspaces

**Comment by Schneegans** [comment]
@uudruid74: If you think that this is either a bug or a feature request, please open a separate issue. However, there are at least three ways to move windows in GNOME, all of which should be working with this extension. Dragging windows in the overview to the left or right, dragging windows to the overview's minimap, and by <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Arrow</kbd>:

https://user-images.githubusercontent.com/829942/150199399-c14c9660-aebc-4e95-8c9d-2de6ee769c41.mp4

**Comment by uudruid74** [comment]
How does dragging windows in the overview manage to move it to another workspace?  I'm pretty sure the person that opened the feature request is asking for exactly this as its why I popped on github.  If this is supposed to work, can you can maybe give some hints as to where to drag to make the window move to the next workspace?  There is no visual indication (such as the cube rotating) to indicate such.  It doesnt appear to work so perhaps this is a bug.  Its unclear what the expected behavior is.

⁣Get BlueMail for Android ​

On Jan 19, 2022, 1:24 PM, at 1:24 PM, Simon Schneegans ***@***.***> wrote:
***@***.***: If you think that this is either a bug or a feature

**Comment by Schneegans** [comment]
The original issue was about moving windows to another workspace in desktop mode (I recreated that one as #18 and renamed this one here to differentiate between the two).

> There is no visual indication

If your pointer is in the drop zone, it will show the move indicator (the little arrows pointing in all directions) you can see this also in the video above. The same happens without the extension and if you try moving windows to the minimap.

Nevertheless, we could consider an option which would rotate the cube when something is dragged over another side of the cube.

**Comment by Schneegans** [comment]
The upcoming release (you can test it by checking out the `main` branch) will allow moving windows to adjacent workspaces by simply dragging the window over the screen's edge. So I think this issue can be closed...
