### ISSUE TITLE
Visualise different wallpapers per workspace

### ISSUE THREAD

**Issue by ivelieu** [Schneegans/Desktop-Cube#127]
## The Motivation
First, I want to say, I really like all of Schneegans' GNOME work, and desktop cube is one of my favourites. Thank you!

I want to have different wallpapers for each workspace, and I think it would be pretty to have them all rendered differently when using the desktop cube. I should preface that I'm not sure if this is actually possible currently, and maybe it is, but I could not find documentation for it. 

In other words, I want to be able to set each of these differently coloured faces to different desktop backgrounds. 
![image](https://github.com/Schneegans/Desktop-Cube/assets/28797826/518f0233-f4eb-4f5f-a4d6-173d0042912a)

## The Solution
I know [here](https://askubuntu.com/questions/75998/is-it-possible-to-have-a-different-background-for-each-workspace) and [here](https://unix.stackexchange.com/questions/7152/can-we-have-different-wallpapers-for-each-workspace-under-gnome) and [here](https://discourse.gnome.org/t/can-i-apply-different-wallpapers-for-each-workspaces-at-the-same-time/7423/3) for different people using plugins or patches for GNOME to get different workspaces, but it seems like they all work on the principle of just switching the desktop background on workspace switch, I think. So I'm not sure how hard it would be for desktop cube to work neatly with these. 

Actually, I want to use a different window manager with GNOME (I am thinking awesomeWM), and I want to cross my fingers that will not break other things, but it also makes me wonder if there was just some way a window manager could specify through some global-ish setting that the desktop cube plugin could read.  Then the desktop cube plugin would figure out from that config file, which wallpapers are used for each workspace. In other words, I'm not sure if it would be better as a separate GNOME plugin or within the desktop cube plugin.

Also, if someone has already figured out how to have different wallpapers per workspace rendered in the plugin already, I might be just making a fool of myself -- I just judge from the fact the showcase videos all have the same desktop background per workspace, that as far as I know it's either not possible or not easy to do after brief experimenting, but I think it'd be really nice if it was both easier to do and documented (in the case that it's already possible to do this.)

## The Alternatives
I know this is a pretty similar request to #17 for animated wallpapers, and #14/#122 for wrap around wallpapers, so I can understand if it is closed. I still just want to open the issue, at least to make aware that I'm interested in this feature.

**Comment by Schneegans** [comment]
Thank you very much for the kind words and the time it took to write this! I have indeed seen the request for such a feature in GNOME several times. However, I think that it should be a separate extension! I see no real reason why such a feature should be part of the Desktop Cube. In fact, I would expect that there are many users who would like to have separate wallpapers without the cube.

One issue will be the dynamic workspaces of GNOME. What happens if you create a new workspace between two others? What if a workspace is removed? What happens if you create a workspace left of the first workspace? I guess this can be solved, but it needs a clear design.

The second issue is that the background-image code in GNOME Shell is fairly complex. I once had a look at [the code](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/background.js) and already the explanation at the beginning of the file is very intimidating... [Hanabi](https://github.com/jeffshee/gnome-ext-hanabi) works pretty well, also in combination with the Desktop Cube. Maybe it would be a possibility to see how they achieved drawing something to the desktop background...

However, the main issue is that I do not have the time to start yet another project :disappointed:. If, at some point, I have the time, this will be one of the first things I would try to implement! In the meantime, I can only suggest that you ask on reddit (https://www.reddit.com/r/gnome/), matrix (https://matrix.to/#/#extensions:gnome.org), or discourse (https://discourse.gnome.org/) if someone would like to try this!

**Comment by dsheeler** [comment]
@Schneegans, first time I read that background comment, it made no sense! Wonder if I read it again if I'd understand, but I kinda doubt it! :)

**Comment by azakharchenko-msol** [comment]
Just to make the issue completely resolved:
https://github.com/blipk/Customised-Workspaces does the job
