### ISSUE TITLE
Dual monitor config issues

### ISSUE THREAD

**Issue by sh7dm** [Schneegans/Desktop-Cube#52]
## Describe the Bug
Weird behavior, these workspaces of connected dual monitor images fly nearly uncontrollably

![Screenshot from 2022-03-06 12-08-02](https://user-images.githubusercontent.com/19504461/156916850-40d49cce-b9bf-438d-bd7e-b46afd49fefc.png)

1. Have 2 monitors attached
2. Swipe to switch workspaces

## System
_Please complete the following information:_
 - Linux distribution Fedora Linux 35
 - Desktop Cube version 8
 - GNOME Shell version: 41.4

**Comment by Schneegans** [comment]
Hi there! Thanks for the report - bad multi-monitor support is [a known limitation](https://github.com/Schneegans/Desktop-Cube/#-limitations) which will be very hard to fix (if not impossible to fix). This is so, because GNOME Shell uses one central perspective for all monitors combined. Therefore, the cube looks distorted on setups with multiple monitors.

Nevertheless, interaction should work nonetheless. Could you explain a bit more what you mean by "images fly nearly uncontrollably"?

**Comment by sh7dm** [comment]
Well, they seem to be mad at first, but pretty much okay if you look at them as combined monitor textures (I know this principle of Mutter doing the compositing).

**Comment by Schneegans** [comment]
Yup. I'll leave this issue open until I have properly checked the code for possible solutions at some point in the future!

**Comment by Schneegans** [comment]
I am currently working on this and it seems fixable! At least on Wayland, I can control the projection matrix of each monitor separately. On X11, there seems to be only one projection matrix. This means that it'll not work properly on X11 if you have a cubes on multiple monitors. However, if you only have the cube on the primary monitor, it'll look good as well. I'll drop a note here if I think that it's ready for testing.

**Comment by Schneegans** [comment]
I just merged a fix for this issue to the `main` branch. If you want to, you may try it by cloning this repo. This is a pretty crazy fix and I hope that it does not break things left and right... I also prepared a little video: https://youtu.be/dpYyn1BXGjU
