### ISSUE TITLE
Please bring back unfolding

### ISSUE THREAD

**Issue by petar-v** [Schneegans/Desktop-Cube#6]
## The Motivation
I love this extension and it brings back nostalgia for sure! Thanks for creating it!
One of the effects that the original compiz didn't have was the workspace unfold animation and I thought it is actually a very pleasing animation. It makes sense for the second workspace to unfold because when scrolling between workspaces without having to go into overview shows them side-by-side, implying that the workspaces are physically next to each other. Now, the second workspace seems simultaneously parallel and perpendicular to the viewpoint based on what angle you're looking at it. Talk about Schrodinger's workspaces! 

## The Solution
Have a setting that allows the user to choose if they want to unfold the cube or not.

## The Alternatives
Can't think of any

**Comment by petar-v** [comment]
I might actually have a go at this in January or whenever I find time :)

**Comment by Schneegans** [comment]
Thanks for the suggestion! It is a good idea to have this as an option once we have a preferences dialog (which itself has quite a high priority). I removed the unfolding for two reasons:
* It reduces the visual noise when entering the overview  since there is much less motion going on.
* I want to implement "cuboid" transitions when switching workspaces in desktop mode (#5). If this should work, we would have the illusion of a cube in all states (except for app grid mode).

**Comment by petar-v** [comment]
Thanks for implementing that! <3
