### ISSUE TITLE
Window panes should have thickness

### ISSUE THREAD

**Issue by johnblommers** [Schneegans/Desktop-Cube#81]
## The Motivation
The original Compiz-Fusion gave us the option to give each window some thickness, so it looked like a pane of glass. IIRC you could even adjust the amount of rounding on the four corners.

## The Solution
Add an option to Desktop-Cube to add a control to enable and tweak window thickness.

## The Alternatives
No alternative comes to mind.

**Comment by Schneegans** [comment]
Hi there & thanks for the suggestion. However, I am pretty sure that this is not possible. The problem is, that window decorations (the borders, the shadows, etc) are drawn by the clients. In theory, the window could appear to have any shape, parts of it could be transparent, there could be holes in the window. For instance, the splash screen of Celestial looks like this:

![splash](https://upload.wikimedia.org/wikipedia/commons/e/e9/Celestia_splash.png)
